export const CHANGE_IN_SEARCH_FIELD = 'CHANGE_IN_SEARCH_FIELD';

export const REQUEST_ROB_PENDING = 'REQUEST_ROB_PENDING';
export const REQUEST_ROB_SUCCESS = 'REQUEST_ROB_SUCCESS';
export const REQUEST_ROB_FAILED = 'REQUEST_ROB_FAILED';